### PR TITLE
Removing node 0.10 build

### PR DESCRIPTION
**Pull request by doowb**
Removing option to build for node 0.10 for now. The npm install is failing when trying to build.

### CODE REVIEW

**Comment by doowb** [comment]
You mean update the package.json devDepencies to use grunt 0.4.1?

**Comment by jonschlinkert** [comment]
I believe if we just put a tilde in front of the versions it will automatically install up to the next major version:

`"~0.4.0" = ">=0.4.0 <0.5.0"`

**Comment by doowb** [comment]
The package says `"grunt": "~0.4.0",` which should be >=0.4.0 and <0.5.0 so it should grab it in travis automatically. I was thinking it was something else since it failed to install one of the npm packages.

**Comment by jonschlinkert** [comment]
Lol that's funny. right at the same time

**Pull request merged**
